--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SteellgoldEstFrancais/PayYourPublicity
branches:
- master
projects:
  PayPublicityEN:
    path: PayPublicityEN/
    icon: "icon.png"
...
