name: PayPublicity
main: Steellg0ld\PayPublicity\Main
version: 0.0.1
api: 3.7.1
load: POSTWORLD
author: Steellg0ld
description: Pay your Publicity in-game !
website: https://github.com/SteellgoldEstFrancais

commands:
 pb:
  description: "§ePayPublicity > Payez votre publicité pour 100.000$"
  usage: "/pb"
  permission: pb.use
 pbv:
  description: "§ePayPublicity > Payez votre publicité pour 10.000$ §c§l[VIP]"
  usage: "/pbv"
  permission: pb.use.vip
 pbvp:
  description: "§ePayPublicity > Payez votre publicité pour 6500$ §c§l[VIP+]"
  usage: "/pbvp"
  permission: pb.use.vipp

permissions:
 pb.use:
  default: true
  description: "§ePayPublicity > Payez votre publicité pour 100.000$"
 pb.use.vip:
  default: op
  description: "§ePayPublicity > Payez votre publicité pour 10.000$"
 pb.use.vipp:
  default: op
  description: "§ePayPublicity > Payez votre publicité pour 6500$"